[buildctl] cleaned-up/refactorized quotek solution builder script.

diff --git a/buildctl b/buildctl
--- a/buildctl
+++ b/buildctl
@@ -2,6 +2,25 @@
 
 PREFIX="/usr/local/qate"
 
+
+function usage() {
+
+  echo -e "\nUsage: $0 <command [command_args]>\n"
+
+  echo "Commands:"
+  echo -e "\n\tbuildall:\n\t\tBuilds all the qate components at once."
+  echo -e "\n\tinstall:\n\t\tPerforms installation of qate in /usr/local."
+  echo -e "\n\tcleanup:\n\t\tCleans all the build files."
+  echo -e "\n\tinit:\n\t\tInstalls the build toolchain and fetches the required 3rd part libs"
+  echo -e "\n\tinitdb <db_type>:\n\t\tInstalls specified Database. Db types: influx08, influx013, postgres."
+  echo -e "\n\tuniverse <db_type> <httpd_type>:\n\t\tBuilds and install the full Quotek env."
+  echo -e "\n\tqwc <httpd_type>:\n\t\tBuilds and configure Web controller. httpd_types: nginx."
+
+}
+
+########## BUILD FUNCTIONS ##########
+
+# Builds The QWC Web Controller.
 function bctl_qwc() {
   echo "Installing QWC With $1"
   pushd ../qwc
@@ -10,6 +29,7 @@ function bctl_qwc() {
   popd
 }
 
+# Builds the IG Markets REST Connector.
 function bctl_igconnector() {
   pushd ../igconnector
   git checkout master
@@ -17,7 +37,7 @@ function bctl_igconnector() {
   popd
 }
 
-
+# Installs and configure the specified Database.
 function bctl_initdb() {
 
   git clone https://github.com/quotekio/db-archive
@@ -45,11 +65,10 @@ function bctl_initdb() {
 
   popd
   rm -rf db-archive
-
 }
 
-
-
+# Installs the build toolchain along 
+# with all the required 3rd part libs. 
 function bctl_init() {
 
   apt-get -y update
@@ -69,9 +88,9 @@ function bctl_init() {
   popd  
 
   rm -rf websocketpp rapidjson rapidxml
-
 }
 
+# Performs the ultimate post-install tasks for qate and qwc.
 function bctl_finish() {
   mkdir /tmp/qate
   touch /var/log/qate.log
@@ -82,7 +101,7 @@ function bctl_finish() {
   ldconfig
 }
 
-
+# Cleans all the binaries object and intermediary build files.
 function bctl_cleanup() {
   make clean
   if  [ -f install_manifest.txt ] ;then
@@ -100,44 +119,42 @@ function bctl_cleanup() {
   
   rm install/compile/headers/*.h
 
-  sdk_cleanup
+  bctl_sdk_cleanup
 
 }
 
-function sdk_cleanup() {
+# Builds and installs the Quotek SDK.
+function bctl_sdk_compile() {
+  cd sdk
+  cmake . && make -j3
+  make install
+  cd ..
+}
+
+# Cleans the Quotek SDK build files.
+function bctl_sdk_cleanup() {
   cd sdk
   ./clean.sh
   cd ..
 }
 
-
-#function bctl_package_SDK() {
-#
-#}
-
-#function bctl_install_SDK() {
-#
-#}
-
+# Creates Makefile for qate.
 function bctl_cmake() {
   cmake -DCMAKE_INSTALL_PREFIX=$PREFIX .
 }
 
+# Builds qate.
 function bctl_compile() {
   make -j3
 }
 
+# Builds qate along with SDK.
 function bctl_compile_all() {
-  cd sdk
-  cmake . && make -j3
-  make install
-  cd ..
+  bctl_sdk_compile
   make -j3
 }
 
-#function bctl_release() {
-#}
-
+# Increments qate build number and puts it inside code.
 function bctl_append_buildnum() {
 
   bnum=`cat .buildctl|grep build_number|sed 's/build_number//'`
@@ -150,14 +167,21 @@ function bctl_append_buildnum() {
   
 }
 
-
+# Installs qate in /usr/local.
 function bctl_install() {
   make install
 }
 
-if [ $# -ge 2 ]
+
+########## ENTRY POINT ###########
+
+echo -e "\nQATE SOLUTION BUILDER V2.1 -- Copyright 2013-2017, Quotek"
+echo    "========================================================="
+
+if [ $# -lt 2 ]
 then
-  PREFIX=$2
+  usage 
+  exit 1
 fi
 
 case $1 in
@@ -174,17 +198,10 @@ case $1 in
     bctl_cleanup
   ;;
 
-  finish)
-    bctl_finish
-  ;;
-
   buildall)
     bctl_append_buildnum
     bctl_cmake
     bctl_compile_all
-    #bctl_release
-    #bctl_install_SDK
-    #bctl_package_SDK
   ;;
 
 
@@ -198,7 +215,7 @@ case $1 in
       echo '[ERROR] qwc not present, leaving..'
       exit
     fi
-    
+
     if [ ! -d ../igconnector ]; then
       echo '[ERROR] igconnector not present, leaving..'
       exit
@@ -217,13 +234,8 @@ case $1 in
     bctl_append_buildnum
     bctl_cmake
     bctl_compile_all
-
-    #bctl_release
-    #bctl_install_SDK
-    #bctl_package_SDK
   ;;
   
-
   install)
     bctl_install
     if [ $# -ge 3 ]
